# Generated by Django 4.1 on 2022-08-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('number_of_pages', models.IntegerField(null=True)),
                ('published_date', models.DateField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
